front-markup
ogatetsu/chat-space pull request #2
Opened 2019-04-14 08:03 UTC by ogatetsu

#what 
chat-spaceの実装
#why
hogehoge

2019-04-14 08:12 UTC, yuki-uchida requested changes
BEMを用いる場合には、複数の場所で使われるCSSは複数のクラスを付与するのではなく、mixinで呼び出す形で記述します

2019-04-14 08:12 UTC, yuki-uchida commented on app/assets/stylesheets/application.scss
> +.create-box{
BEMに従ってクラス命名を行い、アンバサンドを活用した省略形で記述してください

2019-04-14 12:12 UTC, ogatetsu commented on app/assets/stylesheets/application.scss
> +.create-box{
修正しました。

2019-04-14 12:15 UTC, hiroki5123 commented
ビュー画面を作った時は画面のキャウプ茶をこちらに添付してください

2019-04-14 12:17 UTC, ghost requested changes

2019-04-14 12:17 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +%div.message_area
divは指定しなくても要素が生成されるので、全て省略してください

2019-04-14 12:17 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +  %a{ href: 'http://google.co.jp'}
link_toで書いてください

2019-04-14 12:17 UTC, hiroki5123 commented on app/views/layouts/application.html.haml
> +                %i.fa.fa-image
画像のアイコンを押した時にfinderが開かれる仕様になっていないように見えるのですが、いかがでしょうか？

2019-04-14 12:17 UTC, hiroki5123 commented on app/assets/stylesheets/application.scss
> +      color: #fff;
よく使う色は変数化しましょう

2019-04-14 13:06 UTC, ogatetsu commented on app/views/layouts/application.html.haml
> +                %i.fa.fa-image
こちら一応開かれるのですが、いかがでしょうか？

2019-04-14 13:07 UTC, ogatetsu commented on app/views/messages/index.html.haml
> +%div.message_area
了解です

2019-04-14 14:01 UTC, ogatetsu commented on app/assets/stylesheets/application.scss
> +      color: #fff;
了解です

2019-04-14 14:29 UTC, ogatetsu commented on app/views/messages/index.html.haml
> +  %a{ href: 'http://google.co.jp'}
了解です

2019-04-14 14:36 UTC, ogatetsu commented
<img width="1502" alt="スクリーンショット 2019-04-14 21 41 06" src="https://user-images.githubusercontent.com/49158858/56094308-12236080-5f0e-11e9-9201-f091c37a6385.png">

2019-04-15 02:04 UTC, kuroko918 commented on app/views/layouts/application.html.haml
> +    .create-box
この行以下の`= yield`以外の部分はすべてのページで表示されてしまいますが大丈夫ですか？

2019-04-15 02:05 UTC, kuroko918 commented on app/assets/stylesheets/application.scss
> +$white-color: #fff;
application.scssには保守のため、import以外記述しないようにしましょう！

この行以下は適宜外部SCSSファイルに記述し、ここでimportしましょう！

2019-04-15 12:49 UTC, ogatetsu commented
修正しました。

2019-04-15 12:52 UTC, kuroko918 commented on app/assets/stylesheets/style.scss
> +$blue-color: #38aef0;
ここ二つは、せっかく_variable.scssを作成しているため、_variable.scssに書き出し、application/scss でimportしましょう！

2019-04-15 12:52 UTC, kuroko918 commented on config/routes.rb
>    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
不要なコメントは消しておいてください！

2019-04-15 12:58 UTC, ogatetsu commented
修正しました。

2019-04-15 12:58 UTC, kuroko918 commented
LGTMです！

2019-04-15 13:03 UTC, merged